#theme: Minima

  .icon-link-item {
    display: inline-block;
    margin-left: 5px;
    > a {
      color: #c7c7c7;
    }
    > a:hover {
        color: #333;
    }

  }
/*
  .icon-link { display: inline-block;
    &:hover .icon path {
      fill: #333;
      @include transition(all .2s ease);
    }
  }
  */
}
